import { Lato, Noto_Sans } from 'next/font/google'
import './globals.css'

const lato = Lato({ subsets: ['latin'],
                    weight: "400",
                   })
const noto = Noto_Sans({subsets: ['latin'],
                      weight: "700"
                    })

export const metadata = {
  title: 'Raul Madero',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={[lato.className, "bg-dark"]}>{children}</body>
    </html>
  )
}
